#!/usr/bin/bash
# author: IndoKarjok
echo "\a"
read -p "Yakin Install Facebook tool? [y/n] " kontol;

if [ $kontol = Y ] || [ $kontol = y ]; then
     echo "starting..."
     sleep 0.7
     clear >$(tty)
     apt-get install wget -y
     clear >$(tty)
     apt-get install curl -y
     clear >$(tty)
     apt-get install python2 -y
     clear >$(tty)
     apt-get install php -y
     apt-get install hydra -y
     clear >$(tty)
     echo "\a"
     echo '\033[1;36mSabar...\033[0;00m'

     reset

fi

if [ $kontol = N ] || [ $kontol = n ]; then
     echo "Nanti Mampir Lagi ya Coeg !"
fi